Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "services" do |services|
    services.vm.box = "k8s-centos"
    services.vm.hostname = 'k8s-services'

    services.vm.synced_folder ".", "/vagrant", disabled: true

    services.vm.provision "file", source: "bootstrap", destination: "bootstrap"
    services.vm.provision "file", source: "bootstrap.sh", destination: "bootstrap.sh"
    services.vm.provision "shell", inline: "chmod +x bootstrap.sh"
    services.vm.provision "shell", inline: "/home/vagrant/bootstrap.sh", privileged: true

    services.vm.network :private_network, ip: "10.0.0.10"

    services.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "k8s-services"]
    end
  end
end