Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "kubernetes" do |kubernetes|
    kubernetes.vm.box = "centos/7"
    kubernetes.vm.hostname = 'kubernetes'

    kubernetes.vm.synced_folder ".", "/vagrant", disabled: true

    kubernetes.vm.provision "file", source: "authorized_keys", destination: "authorized_keys"
    kubernetes.vm.provision "file", source: "init.sh", destination: "init.sh"
    kubernetes.vm.provision "shell", inline: "chmod +x init.sh"
    kubernetes.vm.provision "shell", inline: "/home/vagrant/init.sh", privileged: true

    kubernetes.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "k8s-centos"]
    end
  end
end